hyperopt:
  executor:
    type: parallel
    workers: 2
  metric: loss
  output_feature: label
  parameters:
    training.learning_rate:
      high: 0.1
      low: 0.001
      scale: log
      type: float
  sampler:
    num_samples: 2
    type: random
  strategy:
    num_samples: null
    type: null
input_features:
- encoder: bert
  level: word
  name: sentence
  preprocessing:
    pretrained_model_name_or_path: bert-base-uncased
    word_tokenizer: hf_tokenizer
  type: text
output_features:
- name: label
  type: category
training:
  batch_size: 16
  early_stop: 3
  eval_batch_size: 64
  learning_rate: 0.01
