input_features:
  - name: ~
    type: text
    level: word
    encoder: rnn
    preprocessing:
      word_tokenizer: space
      pretrained_model_name_or_path: None

output_features:
  - name: ~
    type: category

training:
  learning_rate: 0.01
  batch_size: 16
  eval_batch_size: 64
  early_stop: 1
  
hyperopt:
  output_feature: ${output_features.name}
  metric: ~
  strategy:
    type: ~
    num_samples: ~
  parameters:
    training.learning_rate:
      min: ~
      max: ~
      scale: ~
