metric: loss
parameters:
  training.learning_rate:
    type: float
    lower: 0.001
    upper: 0.01
    space: loguniform
sampler:
  type: ray
  search_alg:
    type: bohb
  scheduler:
    type: hb_bohb
    time_attr: training_iteration
    max_t: 2
    reduction_factor: 2
    stop_last_trials: False
  num_samples: 4
executor:
  type: ray
  cpu_resources_per_trial: 1
  gpu_resources_per_trial: 1
