goal: maximize
metric: accuracy
parameters:
  training.learning_rate:
    type: float
    lower: 0.0001
    upper: 0.01
    space: loguniform
  training.batch_size:
    space: choice
    categories: [16, 32, 64, 128, 256, 512, 1024]
sampler:
  type: ray
  search_alg:
    type: skopt
    max_concurrent: 1
  num_samples: 1
executor:
  type: ray
  cpu_resources_per_trial: 1
  gpu_resources_per_trial: 1
  #kubernetes_namespace: "ray"
