metric: loss
parameters:
  training.learning_rate:
    type: float
    lower: 0.0001
    upper: 0.01
    space: loguniform
sampler:
    type: ray
    search_alg:
      type: random
    num_samples: 2
executor:
  type: ray
  cpu_resources_per_trial: 1
  gpu_resources_per_trial: 1
