goal: minimize
metric: root_mean_squared_error # (or accuracy for classification)
parameters:
  training.learning_rate:
    type: float
    lower: 0.00002
    upper: 0.01
    space: loguniform
sampler:
  type: ray
  search_alg:
    type: skopt 
    max_concurrent: 5
    # type: async_hyperband
    # max_t: 3000
    # grace_period: 900
  num_samples: 50
executor:
  type: ray
  cpu_resources_per_trial: 1
  gpu_resources_per_trial: 1
