metric: loss
sampler:
  type: random
  num_samples: 10
parameters:
  training.learning_rate:
    type: float
    low: 0.0001
    high: 0.01
    scale: log
executor:
  type: parallel
  workers : 2
  


