metric: loss
sampler:
  type: random
  num_samples: 2
parameters:
  training.learning_rate:
    type: float
    low: 0.001
    high: 0.1
    scale: log
  training.optimizer.type:
    type: category
    values: [sgd, adam, adagrad]
executor:
  type: parallel
  workers : 2
  


