metric: loss
parameters:
  training.learning_rate:
    type: float
    lower: 0.001
    upper: 0.01
    space: loguniform
sampler:
  type: ray
  search_alg:
    type: bohb
  scheduler:
    type: hb_bohb
    time_attr: training_iteration
    max_t: 81
    reduction_factor: 3
  num_samples: 27
executor:
  type: ray
  cpu_resources_per_trial: 1
  gpu_resources_per_trial: 2
