input_features:
  - name: ~
    type: image
    encoder: resnet

output_features:
  - name: ~
    type: category

training:
  learning_rate: 0.01
  batch_size: 16
  eval_batch_size: 64
  early_stop: 3
  epochs: 15
  validation_metric: accuracy

hyperopt:
  output_feature:
  metric: ~
  strategy:
    type: ~
    num_samples: ~
  parameters:
    training.learning_rate:
      min: ~
      max: ~
      scale: ~
