model_name: tabconcat
# specify which encoder this model will use for each input feature type
# default values have been provided -- populate only the input types you want
# to modify
input_features:
  - type: text # custom
    encoder: rnn
    preprocessing:
      word_tokenizer: space
      pretrained_model_name_or_path: None
    dropout: 0.5
  - type: binary
    encoder: passthrough # default
  - type: numerical
    encoder: passthrough # default
  - type: category
    encoder: dense # default
  - type: set
    encoder: dense # default
  - type: sequence
    encoder: parallel_cnn # default
  - type: image
    encoder: stacked_cnn # default

# specify which decoder this model will use for each output feature type
# if no decoder is explicitly specified the default will be used
output_features:
  - type: text
  - type: category
  - type: numerical
  - type: sequence
  - type: image
  - type: set

combiner:
  type: concat
  num_fc_layers: 3
  fc_size: 128
  dropout: 0.1

training:
  batch_size: 256
  learning_rate: .001
  # validation_metric: accuracy

parameters:
  combiner.num_fc_layers:
    space: randint
    type: int
    lower: 1
    upper: 8
  combiner.fc_size:
    space: choice
    categories: [128, 256, 512, 1024]
  combiner.dropout:
    space: uniform
    type: float
    lower: 0.0
    upper: 0.1
  training.learning_rate:
    space: loguniform
    type: float
    lower: 0.0001
    upper: 0.01
  training.batch_size:
    space: choice
    categories: [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
